### ISSUE TITLE
Praktikum 5 ül 7/8 - andmebaasi käsklust ei saa teostada

### ISSUE THREAD

**Issue by madiote** [rakenduste-programmeerimine-2019s/rp2019#2]
```
Kitten error { MongoError: not authorized on admin to execute command { insert: "kittens", documents: [[{_id ObjectIdHex("5d98d9e041179605085c7a4d")} {name Red cat} {__v 0}]], ordered: true, writeConcern: { w: "majority" }, lsid: { id: {4 [235 158 247 85 72 121 78 195 145 143 7 109 237 74 76 192]} }, txnNumber: 1.000000, $clusterTime: { clusterTime: 6744379942248644609, signature: { hash: [6 135 90 191 235 178 121 242 205 123 206 156 157 253 32 127 126 250 185 18], keyId: 6742367827379879936.000000 } }, $db: "admin" }
    at Connection.<anonymous> (C:\Users\Madis\Documents\GitHub\rakenduste-programmeerimine\node_modules\mongodb\lib\core\connection\pool.js:466:61)
    at Connection.emit (events.js:189:13)
    at processMessage (C:\Users\Madis\Documents\GitHub\rakenduste-programmeerimine\node_modules\mongodb\lib\core\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (C:\Users\Madis\Documents\GitHub\rakenduste-programmeerimine\node_modules\mongodb\lib\core\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'not authorized on admin to execute command { insert: "kittens", documents: [[{_id ObjectIdHex("5d98d9e041179605085c7a4d")} {name Red cat} {__v 0}]], ordered: true, writeConcern: { w: "majority" }, lsid: { id: {4 [235 158 247 85 72 121 78 195 145 143 7 109 237 74 76 192]} }, txnNumber: 1.000000, $clusterTime: { clusterTime: 6744379942248644609, signature: { hash: [6 135 90 191 235 178 121 242 205 123 206 156 157 253 32 127 126 250 185 18], keyId: 6742367827379879936.000000 } }, $db: "admin" }',
  code: 8000,
  codeName: 'AtlasError',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```

- Andmebaasi `admin` sisselogimine toimib
- IP on lubatud
- Proovisin kasutaja `webdev-admin` rolliks ka määrata _readWriteAnyDatabase_ https://stackoverflow.com/questions/23943651/mongodb-admin-user-not-authorized

**Comment by saarharri** [comment]
![Selection_213](https://user-images.githubusercontent.com/16271010/66259647-037e7d80-e7bc-11e9-9ba2-d57abb85b497.png)

Mis ta teil sellel lehel näitab?

**Comment by madiote** [comment]
![image](https://user-images.githubusercontent.com/43170891/66259690-b51dae80-e7bc-11e9-8e79-651067756737.png)

**Comment by saarharri** [comment]
Isegi kasutaja nimi on sama nagu minul? Kui teete uue kasutaja "add new user" ja seadistate talle vajalikud õigused, kas siis annab ikka sama errori?

**Comment by madiote** [comment]
Jah, kasutajanime muutsin samaks. Errori annab ka uue kasutaja loomisel.

**Comment by madiote** [comment]
Sain tööle - probleem oli selles, et andmebaasile `admin` ei tohi päringuid teha (nagu mongodb connection stringi sees on), siiski tuleb kasutada andmebaasi `test`.
