### ISSUE TITLE
Heroku deploy error (dotenv)

### ISSUE THREAD

**Issue by madiote** [rakenduste-programmeerimine-2019s/rp2019#3]
```
2019-10-05T19:48:55.000000+00:00 app[api]: Build succeeded
2019-10-05T19:48:56.792469+00:00 heroku[web.1]: Starting process with command `npm start`
2019-10-05T19:48:58.953530+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-05T19:48:58.402632+00:00 app[web.1]:
2019-10-05T19:48:58.402661+00:00 app[web.1]: > webapp@1.0.0 start /app
2019-10-05T19:48:58.402663+00:00 app[web.1]: > node server/server.js
2019-10-05T19:48:58.402665+00:00 app[web.1]:
2019-10-05T19:48:58.867084+00:00 app[web.1]: internal/modules/cjs/loader.js:638
2019-10-05T19:48:58.867114+00:00 app[web.1]: throw err;
2019-10-05T19:48:58.867117+00:00 app[web.1]: ^
2019-10-05T19:48:58.867119+00:00 app[web.1]:
2019-10-05T19:48:58.867121+00:00 app[web.1]: Error: Cannot find module 'dotenv'
2019-10-05T19:48:58.867131+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2019-10-05T19:48:58.867134+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2019-10-05T19:48:58.867136+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:692:17)
2019-10-05T19:48:58.867138+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:25:18)
2019-10-05T19:48:58.867140+00:00 app[web.1]: at Object.<anonymous> (/app/server/server.js:6:1)
2019-10-05T19:48:58.867142+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:778:30)
2019-10-05T19:48:58.867144+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-05T19:48:58.867146+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-05T19:48:58.867148+00:00 app[web.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-05T19:48:58.867150+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-05T19:48:58.867152+00:00 app[web.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-05T19:48:58.867154+00:00 app[web.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-05T19:48:58.867156+00:00 app[web.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-05T19:48:58.875618+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-10-05T19:48:58.876003+00:00 app[web.1]: npm ERR! errno 1
2019-10-05T19:48:58.877144+00:00 app[web.1]: npm ERR! webapp@1.0.0 start: `node server/server.js`
2019-10-05T19:48:58.877246+00:00 app[web.1]: npm ERR! Exit status 1
2019-10-05T19:48:58.877486+00:00 app[web.1]: npm ERR!
2019-10-05T19:48:58.877608+00:00 app[web.1]: npm ERR! Failed at the webapp@1.0.0 start script.
2019-10-05T19:48:58.877722+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-05T19:48:58.882633+00:00 app[web.1]:
2019-10-05T19:48:58.882846+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-10-05T19:48:58.882986+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-10-05T19_48_58_879Z-debug.log
2019-10-05T19:48:59.111439+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-05T19:48:58.930600+00:00 heroku[web.1]: Process exited with status 1
2019-10-05T19:49:01.951128+00:00 heroku[web.1]: Starting process with command `npm start`
2019-10-05T19:49:04.310302+00:00 app[web.1]:
2019-10-05T19:49:04.310326+00:00 app[web.1]: > webapp@1.0.0 start /app
2019-10-05T19:49:04.310328+00:00 app[web.1]: > node server/server.js
2019-10-05T19:49:04.310330+00:00 app[web.1]:
2019-10-05T19:49:04.997122+00:00 app[web.1]: internal/modules/cjs/loader.js:638
2019-10-05T19:49:04.997160+00:00 app[web.1]: throw err;
2019-10-05T19:49:04.997162+00:00 app[web.1]: ^
2019-10-05T19:49:04.997164+00:00 app[web.1]:
2019-10-05T19:49:04.997166+00:00 app[web.1]: Error: Cannot find module 'dotenv'
2019-10-05T19:49:04.997168+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2019-10-05T19:49:04.997170+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2019-10-05T19:49:04.997172+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:692:17)
2019-10-05T19:49:04.997174+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:25:18)
2019-10-05T19:49:04.997175+00:00 app[web.1]: at Object.<anonymous> (/app/server/server.js:6:1)
2019-10-05T19:49:04.997177+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:778:30)
2019-10-05T19:49:04.997178+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-05T19:49:04.997180+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-05T19:49:04.997182+00:00 app[web.1]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-05T19:49:04.997183+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-05T19:49:04.997185+00:00 app[web.1]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2019-10-05T19:49:04.997186+00:00 app[web.1]: at startup (internal/bootstrap/node.js:283:19)
2019-10-05T19:49:04.997188+00:00 app[web.1]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019-10-05T19:49:05.013031+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-10-05T19:49:05.015163+00:00 app[web.1]: npm ERR! errno 1
2019-10-05T19:49:05.017305+00:00 app[web.1]: npm ERR! webapp@1.0.0 start: `node server/server.js`
2019-10-05T19:49:05.017535+00:00 app[web.1]: npm ERR! Exit status 1
2019-10-05T19:49:05.017918+00:00 app[web.1]: npm ERR!
2019-10-05T19:49:05.018259+00:00 app[web.1]: npm ERR! Failed at the webapp@1.0.0 start script.
2019-10-05T19:49:05.018517+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-05T19:49:05.029969+00:00 app[web.1]:
2019-10-05T19:49:05.030231+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-10-05T19:49:05.030380+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-10-05T19_49_05_021Z-debug.log
2019-10-05T19:49:05.115034+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-05T19:49:05.093470+00:00 heroku[web.1]: Process exited with status 1
```

`dotenv` on olemas `package.json`is ja kohalikult server käivitub, proovisin seda installida ka `--global` ja `--save-dev` flagidega

**Comment by saarharri** [comment]
Mõned mõtted:
1. `dotenv` peaks olema `dependencies`, mitte `devdependencies`, arenduskeskkonna teegid on webpack, babel, jms
2. `.env` fail on defineeritud `.gitignore` sees. See tähendab, et `.env` fail üldse ei pushita Heroku keskkonda. Herokus tuleks seadistada config vars teistmoodi https://devcenter.heroku.com/articles/config-vars
3. Selle praksi raames tegelikult ei olnudki nõutud, et tehtaks deploy Heroku keskkonda, aga võib-olla see tundus loomulik kulg. Ma lisan selle täienduse praksi lõppu.
